name: io_photobooth
description: I/O Photo Booth app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.3.0-1.0.pre.227

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_storage: ^8.0.4
  analytics:
    path: packages/analytics
  bloc: ^7.0.0
  camera:
    path: packages/camera/camera
  cross_file: ^0.3.1
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  rxdart: ^0.26.0
  image_compositor:
    path: packages/image_compositor
  intl: ^0.17.0
  just_audio: ^0.7.4
  photos_repository:
    path: packages/photos_repository
  authentication_repository:
    path: packages/authentication_repository
  photobooth_ui:
    path: packages/photobooth_ui
  uuid: ^3.0.3
  very_good_analysis: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.2
  mocktail_image_network: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/backgrounds/
    - assets/images/
    - assets/icons/
    - assets/props/google/
    - assets/props/hats/
    - assets/props/eyewear/
    - assets/props/food/
    - assets/props/shapes/
