name: photos_repository
description: repository that manages the photo domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4
  image_compositor:
    path: ../image_compositor

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0
  mocktail: ^0.1.1
