name: photobooth_ui
description: UI Toolkit for the Photobooth Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  flame: ^1.0.0-rc9
  url_launcher: ^6.0.3
  platform_helper:
    path: ../platform_helper

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.3.0

flutter:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
