name: photobooth_ui
description: UI Toolkit for the Photobooth Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.6.0
  flutter:
    sdk: flutter
  platform_helper:
    path: ../platform_helper
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  url_launcher_platform_interface: ^2.1.1
  very_good_analysis: ^4.0.0+1

flutter:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
