name: tensorflow_models_web
description: A tensorflow_models plugin for flutter web
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TensorflowModelsPlugin
        fileName: tensorflow_models_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  tensorflow_models_platform_interface:
    path: ../tensorflow_models_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.3
